version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_DB: ${DB_POSTGRES_DB}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: always      
    ports:
      - ${DB_POSTGRES_PORT}:5432  
      
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
      environment:
        - discovery.type=single-node
      expose:
        - "9200"
      networks:
      - logstash_nwt

  logstash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logstash-container
    volumes:
      - ./syslog.1:/usr/share/logstash/your_log_file.log
    command: logstash -f /usr/share/logstash/config/logstash.conf
    networks:
      - logstash_nwt

networks:
  logstash_nwt:
    driver: bridge
